services:
  # Database for Odoo 19
  db19:
    image: postgres:17
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db_data_19:/var/lib/postgresql/data

  # Database for Odoo 18
  db18:
    image: postgres:16
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db_data_18:/var/lib/postgresql/data

  # Database for Odoo 17
  db17:
    image: postgres:15
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_DB=postgres
    volumes:
      - db_data_17:/var/lib/postgresql/data

  # Odoo 19 Instance
  odoo19:
    image: odoo:19.0
    depends_on:
      - db19
    ports:
      - "8019:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db19
      - USER=odoo
      - PASSWORD=odoo

  # Odoo 18 Instance
  odoo18:
    image: odoo:18.0
    depends_on:
      - db18
    ports:
      - "8018:8069"
    volumes:
    # this path is all team members virtualy access folder
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db18
      - USER=odoo
      - PASSWORD=odoo

  # Odoo 17 Instance
  odoo17:
    image: odoo:17.0
    depends_on:
      - db17
    ports:
      - "8017:8069"
    volumes:
      - ./addons:/mnt/extra-addons
    environment:
      - HOST=db17
      - USER=odoo
      - PASSWORD=odoo

volumes:
  db_data_19:
  db_data_18:
  db_data_17: