// Mock request data shared across staff request pages
export const mockRequests = [
  {
    id: "REQ-001",
    status: "pending",
    purpose: "Field Work",
    startPoint: "MESSOB Center HQ",
    destination: "Adama",
    date: "2026-05-10",
    time: "08:00 AM",
    vehicle: "Toyota Land Cruiser (AA-12345)",
    passengers: 3,
    tripType: "Round Trip",
  },
  {
    id: "REQ-002",
    status: "approved",
    purpose: "Official Meeting",
    startPoint: "MESSOB Center HQ",
    destination: "Bahir Dar",
    date: "2026-05-08",
    time: "09:30 AM",
    vehicle: "Toyota Corolla (AA-67890)",
    passengers: 2,
    tripType: "One-Way",
  },
  {
    id: "REQ-003",
    status: "rejected",
    purpose: "Cargo Delivery",
    startPoint: "MESSOB Center HQ",
    destination: "Hawassa",
    date: "2026-05-06",
    time: "07:00 AM",
    vehicle: "Isuzu Truck (AA-11223)",
    passengers: 1,
    tripType: "Round Trip",
  },
  {
    id: "REQ-004",
    status: "pending",
    purpose: "Official Meeting",
    startPoint: "MESSOB Center HQ",
    destination: "Dire Dawa",
    date: "2026-05-12",
    time: "10:00 AM",
    vehicle: "Not Assigned Yet",
    passengers: 4,
    tripType: "Round Trip",
  },
  {
    id: "REQ-005",
    status: "approved",
    purpose: "Field Work",
    startPoint: "MESSOB Center HQ",
    destination: "Jimma",
    date: "2026-05-07",
    time: "06:30 AM",
    vehicle: "Nissan Patrol (AA-55678)",
    passengers: 5,
    tripType: "One-Way",
  },
];
