{
    'name': 'MESSOB Fleet Management',
    'version': '1.1',
    'category': 'Transportation',
    'summary': 'Digitalizing MESSOB vehicle fleet operations',
    'depends': ['base', 'fleet', 'mail', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'data/sequence_data.xml',
        'views/trip_request_views.xml',
        'views/logs_views.xml',
        'views/audit_views.xml',
        'views/vehicle_views.xml',
        'views/menu_views.xml',
    ],
    'demo': [
        'demo/demo_users.xml',
        'demo/demo_vehicles.xml',
        'demo/demo_drivers.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
