/**
 * Service Worker Registration for PWA Offline Support
 * Automatically generated by vite-plugin-pwa
 * This file registers the service worker and handles updates
 */

import { Workbox } from 'workbox-window';

export function registerSW() {
  if ('serviceWorker' in navigator) {
    const wb = new Workbox('/sw.js');

    // Handle service worker updates
    wb.addEventListener('waiting', () => {
      // Show update notification to user
      if (confirm('New version available! Click OK to update.')) {
        wb.addEventListener('controlling', () => {
          window.location.reload();
        });
        wb.messageSkipWaiting();
      }
    });

    // Handle offline/online status
    wb.addEventListener('installed', (event) => {
      if (!event.isUpdate) {
        console.log('✅ Service worker installed - App ready for offline use');
        // Show notification that app is ready for offline use
        showOfflineReadyNotification();
      }
    });

    // Register the service worker
    wb.register()
      .then((registration) => {
        console.log('✅ Service Worker registered:', registration);
        
        // Check for updates every hour
        setInterval(() => {
          registration.update();
        }, 60 * 60 * 1000);
      })
      .catch((error) => {
        console.error('❌ Service Worker registration failed:', error);
      });

    // Listen for network status changes
    window.addEventListener('online', () => {
      console.log('📡 Back online');
      showOnlineNotification();
    });

    window.addEventListener('offline', () => {
      console.log('📡 App is offline - cached data will be used');
      showOfflineNotification();
    });
  }
}

function showOfflineReadyNotification() {
  if ('Notification' in window && Notification.permission === 'granted') {
    new Notification('MESSOB Fleet', {
      body: 'App is ready to work offline!',
      icon: '/icon-192.png',
      badge: '/icon-192.png',
    });
  }
}

function showOnlineNotification() {
  // Optional: Show toast or notification when back online
  console.log('Network connection restored');
}

function showOfflineNotification() {
  // Optional: Show toast or notification when offline
  console.log('Working in offline mode');
}

// Request notification permission on load (for update notifications)
if ('Notification' in window && Notification.permission === 'default') {
  Notification.requestPermission();
}
